### ISSUE TITLE
Making `v_a%` repeatable

### ISSUE THREAD

**Issue by lacygoill** [chrisbra/matchit#2]
Hello,

as discussed on this question on [stackexchange](https://vi.stackexchange.com/questions/13155/what-do-matchit-vims-a-do/13593?noredirect=1#comment23295_13593), a user could like the ability to select increasingly large regions of text by pressing the visual mapping `v_a%` several times consecutively.

Currently, the mapping is defined on [line 69](https://github.com/chrisbra/matchit/blob/90f0ee7d0f3f997745c87ad2a49bdde3e3cb47d1/plugin/matchit.vim#L69):

    vmap a% <Esc>[%v]%

If `o` is added in front of the `{rhs}` of the mapping (to move the cursor on the opposite corner of the selection):

    vmap a% o<Esc>[%v]%

And if the [issue](https://github.com/chrisbra/matchit/issues/1) involving `]%` is fixed, `v_a%` could probably be used repeatedly.

I'm not sure if `]%` is really needed at the end. It seems that `%` would be enough, since `[%` has already found the previous unmatched token, but maybe I'm missing something. If `%` is used, instead of `]%`, then this issue does not depend on the other one anymore. They become separate.

Also, if the mapping is not needed in select mode (I don't see why it would, but I may have missed something), `xmap` could replace `vmap`:

    xmap a% o<esc>[%v%

**Comment by k-takata** [comment]
The behavior of `v_a%` was changed by #8 and #9, but the behavior might be still unexpected for multiple patterns like #if-#else-#endif.

**Comment by chrisbra** [comment]
closing. If there is a specific error, please create a new issue
