### ISSUE TITLE
problems with pragma when matching keywords in Fortran

### ISSUE THREAD

**Issue by aitzkora** [chrisbra/matchit#21]
Hi, I have a problem with matching fortran keywords when I used pragma compilation directives.
If we mixing fortran and  pagma compilation directive, matching is lost...
for example, going on the first if an pressing '%'
```fortran
program simple
   integer :: a,c

   read(*,*) a
   if (a==2 ) then
#if DEBUG
      print *,a
#endif
     c=a+2
   else 
#if DEBUG
      print *, a
#endif
      c = a -2
   end if
   print *,c
end program simple
```
makes the cursor go on the first '#endif'. Do you know how to correct that. Could I use
a regexp to take that case into account.
If you have any ideas...
Bests regards
marc

**Comment by chrisbra** [comment]
not sure I understand. Where is your cursor, when you hit `%`? And where would you like the cursor to be?

**Comment by k-takata** [comment]
I'm not familiar with fortran, but `ftplugin/fortran.vim` doesn't seem to define `#if`-`#endif` pair in `b:match_words`. Maybe you need to update `b:match_words` by yourself. (See `:help b:match_words`.)

**Comment by aitzkora** [comment]
@chrisba : it would be nice that the cursor goes to the 'else' keywords. #if and #endif creates some interferences to navigate into control structures
@k-takata : it was the sort of information I were looking for.... It hope defining b:match_words enrich the keywords not cancelling the previous definition

**Comment by aitzkora** [comment]
@k-takata : 
I tried let b:match_words = '\<#if\>:\<#endif\>,'. b:match_words on command line but it seems not to do  the job. Have you a example for another langage, how to append some keywords ?
And another question, where I can put these modifications not to modify the system configuration ?
thanks by advance if you know the answers

**Comment by chrisbra** [comment]
So where was your cursor? Can you try the example from the `b:match_words` from the [C ftplugin](https://github.com/vim/vim/blob/5381c7a1628eeca81a46b811158be4cd47ba5815/runtime/ftplugin/c.vim#L41-L44). It looks similar enough to give this a try. Also, are you sure, that matchit is actually run?

**Comment by chrisbra** [comment]
@aitzkora if we figure this out correctly, we can add those examples to the official vim fortran ftplugin.

**Comment by aitzkora** [comment]
@chrisba : yes the problem is clearly not matchit but fortran  ftplugin. You can close this issue, i will post an issue on ftplugin fortran
thanks

**Comment by aitzkora** [comment]
doing manually a 
```vim
:let b:match_words = b:match_words .'^\s*#\s*if(\|def\|ndef\)\>:^\s*#\s*elif\>:^\s*#\s*else\>:^\s*#\s*endif\>'
```
in my fortran file window solve the problem

**Comment by andymass** [comment]
Match-up includes something similar for fortran

https://github.com/andymass/vim-matchup/blob/acf3fca1a0a644bbe3d1478d3be1861c73614d9b/after/ftplugin/fortran_matchup.vim#L17

**Comment by aitzkora** [comment]
thanks, I dit not know this package, I will give a try!
