### ISSUE TITLE
Matchit prevents {count}% from working in Visual mode

### ISSUE THREAD

**Issue by lkintact** [chrisbra/matchit#24]
Hi, your repository is specified in the "Known Bugs and Limitations" section of $VIMRUNTIME/pack/dist/opt/matchit/doc/matchit.txt, so I'm reporting the isssue here.

**To Reproduce:**
1. Run `gvim --clean`
2. Execute `:packadd matchit`
3. Execute `:h index.txt`
5. Start Visual mode with <kbd>v</kbd>, <kbd>V</kbd> or <kbd>Ctrl</kbd><kbd>v</kbd>
6. Type a number, say, 50, and press <kbd>%</kbd>. Instead of extending the selection to the middle of the buffer gVim does nothing.

**Environment:**
 - Vim version [8.2.2146](https://github.com/vim/vim-win32-installer/releases/download/v8.2.2146/gvim_8.2.2146_x86.zip)
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by lkintact** [comment]
Thanks for the fix. I may not understand something, but shouldn't the new, fixed matchit code replace the old one in the [Vim source tree](https://github.com/vim/vim/)? Vim 8.2.2375 still comes with [matchit version 1.17](https://github.com/vim/vim/blob/master/runtime/pack/dist/opt/matchit/plugin/matchit.vim).

**Comment by chrisbra** [comment]
I haven't tagged a new release yet to be submitted to Bram

https://github.com/chrisbra/matchit/tags
