### ISSUE TITLE
can not unmap [%

### ISSUE THREAD

**Issue by BIKA-C** [chrisbra/matchit#32]
I am not so sure why map  [% and ]% to` <NOP>` does not work nor unmap

edit, just realize `<nop>` did not display properly

**Comment by chrisbra** [comment]
so is [% actually being mapped? Check the output of `:verbose nmap [%`. I just tried and it seems to work for me.

**Comment by BIKA-C** [comment]
Here is the `verbose map [%`
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/50717946/155713245-d34730d4-96a7-4ef3-99e8-cdc27c18b592.png">

This is `verbose nmap [%`
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/50717946/155713417-ba3d9b0d-ddfa-4719-b99c-de50f6bc6f61.png">

If I try to do unmap [%, it says no such mapping.

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

**Comment by chrisbra** [comment]
try first to nunmap `[`

**Comment by BIKA-C** [comment]
```
nunmap [
nunmap ]                                                                                                                          
unmap [%
unmap ]%
map [% <nop>
map ]% <nop>
"map [ <C-o>
"map ] <C-i>
```

Still there, [% still works. I have no clue what might be causing it. I just want to map `[' to `<C-O>`

<img width="633" alt="image" src="https://user-images.githubusercontent.com/50717946/155716383-732865da-8381-449e-bc8b-7d8e099a09a3.png">

**Comment by chrisbra** [comment]
Try `:nunmap [%` please. Also try with a minimal vimrc file to rule out some conflicts with other settings.

**Comment by BIKA-C** [comment]
I am able to unmap it with the command `:nunmap [%`, but if I put it into the init.vim, it complains no such keybinding and I am not able to remove it (that is the only thing I have in the init.vim). Is it normal?

**Comment by chrisbra** [comment]
yes, most likely the plugin isn't loaded by the time you want to unmap it.

**Comment by chrisbra** [comment]
so put it into a VimEnter autocommand to have it triggered later
