### ISSUE TITLE
Supporting `syn-keepend` semantics

### ISSUE THREAD

**Issue by ddickstein** [chrisbra/matchit#35]
[OCaml's definition of `b:match_words`](https://github.com/vim/vim/blob/master/runtime/ftplugin/ocaml.vim#L67-L75) has a bug in the following scenario:
```ocaml
1 let x =
2   let module Foo = struct
3     let a = 0
4     let b = 1
5   end
6   in
7   Foo.a
8 ;;
```
The correct pairing here would be `let` on line 1 is paired with the `;;` on line 8, the `let` on line 2 is paired with the `in` on line 6, and the `struct` on line 2 is paired with the `end` on line 5. Matchit incorrectly pairs the `let` on line 3 with the `;;` on line 8 and the `let` on line 4 with the `in` on line 6. If it supported [`syn-keepend`](https://vimhelp.org/syntax.txt.html#%3Asyn-keepend) semantics, we would be able to say that `let` should not match across an unmatched `end`.

**Comment by chrisbra** [comment]
Unfortunately, there is no way to query the `syn-keepend` syntax properties, thus there is no way for matchit to guess the proper jump point.

**Comment by ddickstein** [comment]
Is this a limitation of `searchpair`?

**Comment by chrisbra** [comment]
not only `searchpair()` . There is no API to query information about what parts of a buffer belong to what syntax group, except for querying each column separately to what syntax item it belongs to.

**Comment by ddickstein** [comment]
Yeah, I don't think matchit should be leveraging syntax groups. What I mean is, is there some functionality that is missing in the API to have keepend-like pair navigation, and if not, should/could that be something that `searchpair` provided? What would the "necessary and sufficient" need to be here for this to work? I'd like to request it.
