### ISSUE TITLE
`:MatchEnable` and `:MatchDisable` Commands Not Available

### ISSUE THREAD

**Issue by Ddystopia** [chrisbra/matchit#38]
I'm using the matchit.vim plugin in my Neovim setup with the lazy.nvim package manager. The plugin seems to be loading correctly, as I can see `matchit.vim` in the list of sourced scripts when I run `:scriptnames`. However, the `:MatchEnable` and `:MatchDisable` commands are not available. When I try to run these commands, I get an error message saying that the command doesn't exist.

Interestingly, the `:MatchDebug` command is available and setting `b:match_debug` to 1.
```
:echo b:match_debug
1
```

## Steps to Reproduce

1. Open Neovim.
2. Run `:MatchEnable` or `:MatchDisable`.
3. Observe that these commands are not available.
4. Run `:MatchDebug`.
5. Observe that this command is available and sets `b:match_debug` to 1.

## Expected Behavior
The `:MatchEnable`, `:MatchDisable`, and `:MatchDebug` commands should all be available. `:MatchEnable` and `:MatchDisable` should enable or disable the matchit plugin when run, and `:MatchDebug` should set `b:match_debug` to 1.

## Actual Behavior
When I try to run `:MatchEnable` or `:MatchDisable`, I get an error message saying that the command doesn't exist. However, the `:MatchDebug` command works as expected.

## Environment
- Neovim version: 
```
❯ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

Run :checkhealth for more info
```
- Plugin manager: lazy.nvim
- Operating system: Arch Linux

I would appreciate any help in resolving this issue. Thank you!

**Comment by chrisbra** [comment]
how did you run install it?

**Comment by Ddystopia** [comment]
This seems to me to be sufficient as a minimal reproducible example

init.lua:

```lua
local M = {
  'chrisbra/matchit'
}

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({ M }, {})
```

Open neovim with that config `nvim -u path/to/init.lua`

**Comment by chrisbra** [comment]
Wait, before I go into the defaults of Neovim and lazynvim can you please check, if your checked out version of matchit contains: 

https://github.com/chrisbra/matchit/blob/master/plugin/matchit.vim#L109-L120

It it works, please clone as package to rule out lazy.nvim and see if it works then.

**Comment by chrisbra** [comment]
In particular, please make sure you are not accidentally using https://github.com/neovim/neovim/tree/master/runtime/pack/dist/opt/matchit

**Comment by Ddystopia** [comment]
Oh, I think I am using https://github.com/neovim/neovim/tree/master/runtime/pack/dist/opt/matchit

![image](https://github.com/chrisbra/matchit/assets/63151578/87c9d164-e213-4d61-9690-e10764ee5bd2)

**Comment by chrisbra** [comment]
ah makes sense. I should probably send out the new matchit for inclusion with Vim. I'll do this soon (and neovim should also then get it eventually)

**Comment by chrisbra** [comment]
I tagged a new release and will send and update to Vim. So closing.

**Comment by chrisbra** [comment]
I sent an update to Bram: https://github.com/vim/vim/pull/12611
