### ISSUE TITLE
[Feature request] Make t motion match self closed tags

### ISSUE THREAD

**Issue by dmtrKovalenko** [chrisbra/matchit#42]
### Problem

Right now `dat` will remove xml-like tags 

```xml
<tag attribute>
  <any-other tag>
</tag>
```

But not tags like this

```xml
<tag attribute />
```

While they are a standard and using in a lot of different languages and framework: React-jsx, html, svg, etc

### Expected behavior

Make `t` motion match the self-closed tags as well.

I will be happy to help and  open a pr for that

**Comment by chrisbra** [comment]
That is documented behaviour for `:h tag-blocks`. This has nothing to do with the matchit plugin, but feel free to open an issue over at vim/vim please.
