### ISSUE TITLE
delete doc/tags please

### ISSUE THREAD

**Issue by razamatan** [chrisbra/matchit#48]
most plugin managers for vim automatically generates doc/tags files using `:helptags` automatically.  as this repo has checked in doc/tags, it can go out of sync w/ the matchit.txt file over time and cause merge conflicts.

as a result, nearly all other plugins do not have have the doc/tags file checked in.in doc/tags, it can go out of sync w/ the matchit.txt file over time and cause conflicts.

please remove and add a .gitignore to prevent readding it.  thanks.

**Comment by razamatan** [comment]
see https://vi.stackexchange.com/questions/19947/why-are-helptags-not-shipped-with-plugins

**Comment by razamatan** [comment]
also a biased sample of some plugins that explicitly have setup `.gitignores` to avoid this problem:

```
$ grep -Hirn doc/tags *
Recover.vim/.gitignore:14:doc/tags
ctrlp.vim/doc/ctrlp.cnx:1110:      例如: set tags+=doc/tags
ctrlp.vim/doc/ctrlp.txt:1176:      E.g. set tags+=doc/tags
dart-vim-plugin/.gitignore:1:doc/tags
grep: matchit/.git/index: binary file matches
rust.vim/.gitignore:1:/doc/tags
slimv/.gitignore:1:doc/tags
supertab/.gitignore:3:doc/tags
undotree/.gitignore:1:doc/tags
grep: vim-colors-solarized/.git/index: binary file matches
vim-dispatch/.gitignore:1:/doc/tags
vim-elixir/.gitignore:3:doc/tags
vim-latex/.gitignore:39:doc/tags
vim-lsc/.gitignore:1:doc/tags
vim-projectionist/.gitignore:1:/doc/tags
vim-ragtag/.gitignore:1:doc/tags
vim-sleuth/.gitignore:1:/doc/tags
vim-speeddating/.gitignore:1:/doc/tags
vim-surround/.gitignore:1:/doc/tags
vim-terraform/.gitignore:1:/doc/tags
```

**Comment by chrisbra** [comment]
I'll remove it thanks

**Comment by razamatan** [comment]
please delete the checked-in doc/tags file itself.  it'll still be tracked: https://stackoverflow.com/questions/9750606/git-still-shows-files-as-modified-after-adding-to-gitignore
