### ISSUE TITLE
Svelte support?

### ISSUE THREAD

**Issue by 231tr0n** [chrisbra/matchit#49]
Hi chrisbra! Is it possible to add svelte support to this plugin?

**Comment by chrisbra** [comment]
I don't understand the question. How does svelte differ in that this plugin needs to adjust for this?

**Comment by 231tr0n** [comment]
> I don't understand the question. How does svelte differ in that this plugin needs to adjust for this?

Basically, you cannot navigate between html tags in .svelte files. That is the issue

**Comment by chrisbra** [comment]
I suppose you need to configure the svelte filetype plugin for matchit support, similar to what e.g. the html plugin does. 
See e.g. [here](https://github.com/vim/vim/blob/master/runtime/ftplugin/html.vim) for html and [here](https://github.com/vim/vim/blob/master/runtime/ftplugin/svelte.vim) for svelte. Note how the svelte filetype plugin does not define any `b:match_words` variables. 

Please go ahead and create a PR against the Vim repository to add matchit support for Svelte file types then.
